# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.4

# Default target executed when no arguments are given to make.
default_target: all

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /tmp/wiki2latex

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /tmp/wiki2latex

# Include the progress variables for this target.
include CMakeFiles/progress.make

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/wiki2latex/CMakeFiles $(CMAKE_ALL_PROGRESS)
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/wiki2latex/CMakeFiles 0

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean

# The main clean target
clean/fast: clean

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1

#=============================================================================
# Target rules for targets named wiki2latex

# Build rule for target.
wiki2latex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wiki2latex

# fast build rule for target.
wiki2latex/fast:
	$(MAKE) -f CMakeFiles/wiki2latex.dir/build.make CMakeFiles/wiki2latex.dir/build

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/wiki2latex.dir/build.make CMakeFiles/wiki2latex.dir/main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/wiki2latex.dir/build.make CMakeFiles/wiki2latex.dir/main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/wiki2latex.dir/build.make CMakeFiles/wiki2latex.dir/main.s

# target to build an object file
parser.o:
	$(MAKE) -f CMakeFiles/wiki2latex.dir/build.make CMakeFiles/wiki2latex.dir/parser.o

# target to preprocess a source file
parser.i:
	$(MAKE) -f CMakeFiles/wiki2latex.dir/build.make CMakeFiles/wiki2latex.dir/parser.i

# target to generate assembly for a file
parser.s:
	$(MAKE) -f CMakeFiles/wiki2latex.dir/build.make CMakeFiles/wiki2latex.dir/parser.s

# target to build an object file
retezce.o:
	$(MAKE) -f CMakeFiles/wiki2latex.dir/build.make CMakeFiles/wiki2latex.dir/retezce.o

# target to preprocess a source file
retezce.i:
	$(MAKE) -f CMakeFiles/wiki2latex.dir/build.make CMakeFiles/wiki2latex.dir/retezce.i

# target to generate assembly for a file
retezce.s:
	$(MAKE) -f CMakeFiles/wiki2latex.dir/build.make CMakeFiles/wiki2latex.dir/retezce.s

# target to build an object file
retezec.o:
	$(MAKE) -f CMakeFiles/wiki2latex.dir/build.make CMakeFiles/wiki2latex.dir/retezec.o

# target to preprocess a source file
retezec.i:
	$(MAKE) -f CMakeFiles/wiki2latex.dir/build.make CMakeFiles/wiki2latex.dir/retezec.i

# target to generate assembly for a file
retezec.s:
	$(MAKE) -f CMakeFiles/wiki2latex.dir/build.make CMakeFiles/wiki2latex.dir/retezec.s

# target to build an object file
zasobnik.o:
	$(MAKE) -f CMakeFiles/wiki2latex.dir/build.make CMakeFiles/wiki2latex.dir/zasobnik.o

# target to preprocess a source file
zasobnik.i:
	$(MAKE) -f CMakeFiles/wiki2latex.dir/build.make CMakeFiles/wiki2latex.dir/zasobnik.i

# target to generate assembly for a file
zasobnik.s:
	$(MAKE) -f CMakeFiles/wiki2latex.dir/build.make CMakeFiles/wiki2latex.dir/zasobnik.s

# Help Target
help::
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... wiki2latex"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... retezce.o"
	@echo "... retezce.i"
	@echo "... retezce.s"
	@echo "... retezec.o"
	@echo "... retezec.i"
	@echo "... retezec.s"
	@echo "... zasobnik.o"
	@echo "... zasobnik.i"
	@echo "... zasobnik.s"



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0

